### ISSUE TITLE
KSRGAP Kerbal traits showing up in astronaut complex. 

### ISSUE THREAD

**Issue by UltraVioletUwU** [caerfinon/KerbinSideRemasteredGAP#78]
The kerbals from this mod are showing up in the astronaut complex list for hire, I assume this is not intentional and is quite problematic as it's lowering the amount of normal kerbals that I can hire. 
[KSP.log](https://github.com/user-attachments/files/16389494/KSP.log)

**Comment by caerfinon** [comment]
The switchover from tourists to other kerbal types was made in version  v2.1.2 of the mod.  Reverting to use [v2.1.1](https://github.com/caerfinon/KerbinSideRemasteredGAP/releases/tag/v2.1.1) will correct this issue but will also remove other advancements current in v2.1.7

An alternative is to use a mod that allows you to "manage" your kerbals once hired.  You could hire a service kerbal and then change that kerbal to be an pilot, engineer, or scientist.  This can also be achieved by directly editing the Roster section of the persistent.sfs  file to change the kerbals directly. 

In my game play I relied on the use of either TRP-Hire or MKS  which replaces the hiring functions of the Astronaut Complex and allows you to choose which type of Kerbal you want to hire rather than choosing from available candidates.  The former only affects the hiring process. the latter adds additional game complexities you may not want to include in your game play. 

KSRGAP mod is currently not under development and an updated version by me is not planned.  The mod is released under an MIT license and individuals are free to fork my version and make their own versions for their own use or to distribute widely to the community.
